apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-example
  namespace: argocd
spec:
  dnsNames:
    - "certificate-example.example.com"
  secretName: certificate-example
  issuerRef:
    name: stage-le-issuer
    kind: ClusterIssuer