apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: stage-le-issuer
spec:
  acme:
    email: letsencrypt_notification_email@example.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: stage-le-issuer
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
      selector:
        dnsZones:
        - 'example.com'