apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
#    server: https://acme-staging-v02.api.letsencrypt.org/directory
# при переключении со staging нужно заменить в Metadata:name privateKeySecretRef:name "letsencrypt-staging" на "letsencrypt-prod"
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 142608@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx